# Generated by Django 4.1 on 2022-09-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='any_title', max_length=100),
        ),
    ]
